In [ ]:
import pandas as pd
value_n_list = ["Andrew", "Phillip", "Jhon", "Luis", "Maria", "Pedro", "Ana", "Carlos", "Laura", "Diego"]
print(value_n_list)
value_w_list = [50, 78, 91.5, 71.5, 62, 85, 55, 75, 68, 70]
value_h_list = [1.76, 1.87, 1.69, 1.80, 1.65, 1.78, 1.60, 1.70, 1.72, 1.75]
data_dict= {"Name": value_n_list,
            "Weight": value_w_list,
            "Height": value_h_list}
print(data_dict)
df= pd.DataFrame(data_dict)
print(df)
df

['Andrew', 'Phillip', 'Jhon', 'Luis', 'Maria', 'Pedro', 'Ana', 'Carlos', 'Laura', 'Diego']
{'Name': ['Andrew', 'Phillip', 'Jhon', 'Luis', 'Maria', 'Pedro', 'Ana', 'Carlos', 'Laura', 'Diego'], 'Weight': [50, 78, 91.5, 71.5, 62, 85, 55, 75, 68, 70], 'Height': [1.76, 1.87, 1.69, 1.8, 1.65, 1.78, 1.6, 1.7, 1.72, 1.75]}
      Name  Weight  Height
0   Andrew    50.0    1.76
1  Phillip    78.0    1.87
2     Jhon    91.5    1.69
3     Luis    71.5    1.80
4    Maria    62.0    1.65
5    Pedro    85.0    1.78
6      Ana    55.0    1.60
7   Carlos    75.0    1.70
8    Laura    68.0    1.72
9    Diego    70.0    1.75

      Name  Weight  Height
0   Andrew    50.0    1.76
1  Phillip    78.0    1.87
2     Jhon    91.5    1.69
3     Luis    71.5    1.80
4    Maria    62.0    1.65
5    Pedro    85.0    1.78
6      Ana    55.0    1.60
7   Carlos    75.0    1.70
8    Laura    68.0    1.72
9    Diego    70.0    1.75

In [ ]:
df ["bmi"] = df["Weight"] / (df["Height"] ** 2)
df

      Name  Weight  Height        bmi
0   Andrew    50.0    1.76  16.141529
1  Phillip    78.0    1.87  22.305471
2     Jhon    91.5    1.69  32.036693
3     Luis    71.5    1.80  22.067901
4    Maria    62.0    1.65  22.773186
5    Pedro    85.0    1.78  26.827421
6      Ana    55.0    1.60  21.484375
7   Carlos    75.0    1.70  25.951557
8    Laura    68.0    1.72  22.985398
9    Diego    70.0    1.75  22.857143

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Weight  10 non-null     float64
 2   Height  10 non-null     float64
 3   bmi     10 non-null     float64
dtypes: float64(3), object(1)
memory usage: 452.0+ bytes

In [ ]:
df.shape

(10, 4)

In [ ]:
df.describe()

          Weight     Height        bmi
count  10.000000  10.000000  10.000000
mean   70.600000   1.732000  23.543067
std    12.771061   0.077574   4.120847
min    50.000000   1.600000  16.141529
25%    63.500000   1.692500  22.127294
50%    70.750000   1.735000  22.815165
75%    77.250000   1.775000  25.210017
max    91.500000   1.870000  32.036693

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Weight,10.0,70.600000,12.771061,50.000000,63.500000,70.750000,77.250000,91.500000
Height,10.0,1.732000,0.077574,1.600000,1.692500,1.735000,1.775000,1.870000
bmi,10.0,23.543067,4.120847,16.141529,22.127294,22.815165,25.210017,32.036693

In [ ]:
df.describe(include="O")

          Name
count       10
unique      10
top     Andrew
freq         1

In [ ]:
df.describe(include="all")

          Name     Weight     Height        bmi
count       10  10.000000  10.000000  10.000000
unique      10        NaN        NaN        NaN
top     Andrew        NaN        NaN        NaN
freq         1        NaN        NaN        NaN
mean       NaN  70.600000   1.732000  23.543067
std        NaN  12.771061   0.077574   4.120847
min        NaN  50.000000   1.600000  16.141529
25%        NaN  63.500000   1.692500  22.127294
50%        NaN  70.750000   1.735000  22.815165
75%        NaN  77.250000   1.775000  25.210017
max        NaN  91.500000   1.870000  32.036693

## ¿Qué es la Desviación Estándar (std)?

La **desviación estándar (std)** es una medida fundamental en estadística que nos dice cuánto se dispersan o se agrupan los valores de un conjunto de datos alrededor de su media (promedio). En otras palabras, mide la variabilidad de los datos. Un valor bajo indica que los puntos de datos tienden a estar cerca de la media, mientras que un valor alto indica que los puntos de datos están más dispersos en un rango más amplio de valores.

### Pasos para calcular la Desviación Estándar:

1.  **Calcula la media (promedio) de tus datos (μ o x̄):** Suma todos los valores y divídelos por el número total de valores.

    *   **Ejemplo:** Si tus datos son `[1, 2, 3, 4, 5]`, la media es `(1+2+3+4+5) / 5 = 15 / 5 = 3`.

2.  **Calcula la desviación de cada punto de datos con respecto a la media:** Resta la media a cada uno de tus puntos de datos.

    *   **Ejemplo:**
        *   `1 - 3 = -2`
        *   `2 - 3 = -1`
        *   `3 - 3 = 0`
        *   `4 - 3 = 1`
        *   `5 - 3 = 2`

3.  **Eleva al cuadrado cada una de esas desviaciones:** Esto se hace para eliminar los signos negativos (ya que una distancia no puede ser negativa) y para dar más peso a las desviaciones más grandes.

    *   **Ejemplo:**
        *   `(-2)^2 = 4`
        *   `(-1)^2 = 1`
        *   `(0)^2 = 0`
        *   `(1)^2 = 1`
        *   `(2)^2 = 4`

4.  **Suma todos los resultados elevados al cuadrado:** Obtendrás la suma de los cuadrados de las desviaciones.

    *   **Ejemplo:** `4 + 1 + 0 + 1 + 4 = 10`

5.  **Divide la suma de los cuadrados por el número total de puntos de datos (N) o por (N-1):**
    *   Si tienes la población completa de datos, divides por `N`. Este es el **parámetro** de desviación estándar (σ).
    *   Si tienes una muestra de los datos (que es lo más común en la práctica), divides por `N-1`. Este es el **estadístico** de desviación estándar (s). Dividir por `N-1` corrige un sesgo que subestimaría la desviación estándar de la población si solo usáramos `N` para una muestra.

    *   **Ejemplo (para una muestra):** `10 / (5 - 1) = 10 / 4 = 2.5`
    *   Este resultado intermedio es la **varianza**.

6.  **Toma la raíz cuadrada del resultado del paso 5:** Esto te devolverá la desviación estándar en las mismas unidades que tus datos originales.

    *   **Ejemplo:** `sqrt(2.5) ≈ 1.58`

### Fórmula de la Desviación Estándar:

La fórmula general para la **desviación estándar de una muestra (s)** es:

```
s = √[ Σ (xi - x̄)² / (n - 1) ]
```

Donde:
*   `s` = Desviación estándar de la muestra
*   `Σ` = Símbolo de sumatoria (significa 'sumar todo')
*   `xi` = Cada valor individual en el conjunto de datos
*   `x̄` = La media (promedio) de la muestra
*   `n` = El número total de puntos de datos en la muestra

Para la **desviación estándar de una población (σ)**, la fórmula es:

```
σ = √[ Σ (xi - μ)² / N ]
```

Donde:
*   `σ` = Desviación estándar de la población
*   `μ` = La media (promedio) de la población
*   `N` = El número total de puntos de datos en la población

En la salida de `df.describe()`, la columna `std` representa precisamente esta desviación estándar, calculada generalmente como la desviación estándar de una **muestra** (dividiendo por `n-1`), lo cual es el comportamiento predeterminado en Pandas y la mayoría de las librerías estadísticas, a menos que se especifique lo contrario.